# Output limits and gains.
# 0.85 avoids the brownouts/current limiting that tend to appear at a hard 100%.
MAX_PWM = 0.85
PWM_FREQUENCY_HZ = 1000
LINEAR_GAIN = 1.0
ANGULAR_GAIN = 1.0

# Flip a value to -1.0 if a motor spins backwards.
LEFT_MOTOR_DIRECTION = 1.0
RIGHT_MOTOR_DIRECTION = 1.0

# Safety.
CMD_TIMEOUT_SECONDS = 1.0
NUMERIC_ZERO_EPSILON = 1e-9

# Adaptive S-curve profile.
PROFILE_PERIOD = 0.02
IMMEDIATE_DELTA = 0.04
MIN_RAMP_TIME = 0.04
MAX_RAMP_TIME = 1.60
DIRECTION_CHANGE_MIN_RAMP = 0.45
TARGET_UPDATE_EPSILON = 0.002

STRAIGHT_RAMP_FACTOR = 0.75
CURVE_RAMP_FACTOR = 0.45
PIVOT_RAMP_FACTOR = 0.50
STOP_RAMP_FACTOR = 0.30

# BTS7960 GPIO pins, BCM numbering.
LEFT_RPWM_PIN = 12
LEFT_LPWM_PIN = 13
LEFT_REN_PIN = 27
LEFT_LEN_PIN = 17

RIGHT_RPWM_PIN = 18
RIGHT_LPWM_PIN = 19
RIGHT_REN_PIN = 22
RIGHT_LEN_PIN = 23
