// GENERATED by tools/extract_arm_canvas.py from the delivered renderer.
'use strict';
const $=id=>document.getElementById(id);
const add=(a,b)=>a.map((v,i)=>v+b[i]), sub=(a,b)=>a.map((v,i)=>v-b[i]), scale=(a,s)=>a.map(v=>v*s);
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0), norm=a=>Math.hypot(...a), cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const I=()=>[[1,0,0],[0,1,0],[0,0,1]], tr=A=>A[0].map((_,i)=>A.map(r=>r[i]));
const mv=(A,v)=>A.map(r=>dot(r,v)), mm=(A,B)=>A.map(r=>tr(B).map(c=>dot(r,c)));

const K={add,sub,scale,dot,norm,cross,tr,mv,clamp:(v,a,b)=>Math.min(b,Math.max(a,v))};
let snapshot=null,g={},target=null,selected=-1,mode='pose';
let camera={az:-1.1,el:.24,zoom:1};
const fmt=(v,n=2)=>{let x=Math.abs(v)<.5*10**(-n)?0:v;return x.toFixed(n);};
window.MotionUI={drawPath(){
 const points=snapshot.preview?.points;
 if(points)points.slice(1).forEach((p,i)=>line(points[i],p,'#ffb36a',3,[5,5]));
}};
const canvas=$('scene'),ctx=canvas.getContext('2d');let W=0,H=0;
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function project(p){
 const reach=g.l1+g.l2+g.l3+g.e56+Math.max(g.d,K.norm([g.cx,g.cy,g.cz]))+g.h+.05,s=Math.min(W,H)*.68/Math.max(reach,.1)*camera.zoom,ca=Math.cos(camera.az),sa=Math.sin(camera.az),ce=Math.cos(camera.el),se=Math.sin(camera.el);
 const z=p[2]-g.h*.4-.2*(g.l1+g.l2+g.l3),right=-sa*p[0]+ca*p[1],up=-se*(ca*p[0]+sa*p[1])+ce*z;
 return [W*.48+s*right,H*.57-s*up,ce*(ca*p[0]+sa*p[1])+se*z];
}
function line(a,b,color,width=1,dash=[]){const A=project(a),B=project(b);ctx.beginPath();ctx.moveTo(A[0],A[1]);ctx.lineTo(B[0],B[1]);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.lineCap='round';ctx.stroke();ctx.setLineDash([]);}
function label(p,text,color='#cad7e9',dx=9,dy=-10){const a=project(p);ctx.font='12px ui-monospace,monospace';ctx.fillStyle='#0e1725';ctx.fillRect(a[0]+dx-3,a[1]+dy-12,ctx.measureText(text).width+6,17);ctx.fillStyle=color;ctx.fillText(text,a[0]+dx,a[1]+dy);}
function arrow(p,v,color,name,len){const end=K.add(p,K.scale(v,len));line(p,end,color,2);const a=project(p),b=project(end),theta=Math.atan2(b[1]-a[1],b[0]-a[0]);ctx.beginPath();ctx.moveTo(b[0],b[1]);ctx.lineTo(b[0]-7*Math.cos(theta-.4),b[1]-7*Math.sin(theta-.4));ctx.moveTo(b[0],b[1]);ctx.lineTo(b[0]-7*Math.cos(theta+.4),b[1]-7*Math.sin(theta+.4));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();if(name)label(end,name,color,5,-4);}
function triad(p,R,len,ghost=false){K.tr(R).forEach((v,i)=>arrow(p,v,ghost?'#ffb36a':['#ff777f','#69d591','#6baaff'][i],ghost?'':['xₜ','yₜ','zₜ'][i],len));}
function cuboid(center,R,size,colors){
 const pts=Array.from({length:8},(_,i)=>K.add(center,K.mv(R,size.map((v,j)=>(i&(1<<j)?1:-1)*v/2))));
 const faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]];
 faces.map((ids,i)=>({ids,i,depth:ids.reduce((s,j)=>s+project(pts[j])[2],0)/4})).sort((a,b)=>a.depth-b.depth).forEach(({ids,i})=>{
  ctx.beginPath();ids.forEach((j,k)=>{const p=project(pts[j]);if(k)ctx.lineTo(p[0],p[1]);else ctx.moveTo(p[0],p[1]);});ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();ctx.lineWidth=1;ctx.strokeStyle='#576779';ctx.stroke();
 });
}
function jointRing(p,axis,r,color){const helper=Math.abs(axis[2])<.9?[0,0,1]:[0,1,0];let u=K.cross(axis,helper);u=K.scale(u,1/K.norm(u));const v=K.cross(axis,u);let last=null;for(let i=0;i<=32;i++){const a=i/32*Math.PI*2,point=K.add(p,K.add(K.scale(u,r*Math.cos(a)),K.scale(v,r*Math.sin(a))));if(last)line(last,point,color,2);last=point;}}
function draw(){
 if(!W||!H||!snapshot)return;ctx.clearRect(0,0,W,H);const f=snapshot.fk,reach=g.l1+g.l2+g.l3+g.d,grid=Math.max(.2,Math.ceil(reach*10)/10),step=grid>1?.2:.1;
 for(let x=-grid;x<=grid+.0001;x+=step){line([x,-grid,0],[x,grid,0],'#233149',1);line([-grid,x,0],[grid,x,0],'#233149',1);}
 const unit=Math.max(.1,Math.min(.25,reach*.35));arrow([0,0,0],[1,0,0],'#e6757d','X',unit);arrow([0,0,0],[0,1,0],'#68bd85','Y',unit);arrow([0,0,0],[0,0,1],'#71a2eb','Z',unit);
 window.MotionUI?.drawPath();
 if(target){line([target.p[0],target.p[1],0],target.p,'#a77144',1,[4,5]);if(mode==='pose')triad(target.p,target.R,unit*.65,true);const a=project(target.p);ctx.strokeStyle='#ffb36a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(a[0],a[1],7,0,Math.PI*2);ctx.moveTo(a[0]-12,a[1]);ctx.lineTo(a[0]+12,a[1]);ctx.moveTo(a[0],a[1]-12);ctx.lineTo(a[0],a[1]+12);ctx.stroke();label(target.p,'objetivo B','#ffb36a',12,22);}
 line([f.p[0],f.p[1],0],f.p,'#41696c',1,[3,6]);
 const segments=f.points.slice(1,5).map((p,i)=>({a:f.points[i],b:p,i,depth:(project(p)[2]+project(f.points[i])[2])/2})).sort((a,b)=>a.depth-b.depth);
 for(const s of segments){if(K.norm(K.sub(s.a,s.b))<1e-7)continue;line(s.a,s.b,'#09111b',17);line(s.a,s.b,s.i===4?'#cbd9ec':s.i===0?'#586981':'#359f9c',12);line(s.a,s.b,s.i===4?'#e3edf9':s.i===0?'#8b9aad':'#75ece0',3);}
 if(g.e56>1e-8)line(f.wrist,f.flange.p,'#b7c7d5',7);
 if(g.d>1e-8)cuboid(K.add(f.flange.p,K.mv(f.flange.R,[g.d/2,0,0])),f.flange.R,[g.d,.035,.008],['#e8bb25','#fff27a','#f1d044']);
 const mountAnchor=K.add(f.flange.p,K.mv(f.flange.R,[g.cx,0,0]));line(mountAnchor,f.camera.p,'#abb6c8',2,[3,3]);
 cuboid(f.camera.p,f.camera.R,[.04,.025,.035],['#c4cedd','#ffffff','#e6edf5']);
 const ringSize=Math.max(.012,reach*.028);
 f.origins.map((p,i)=>({p,i,depth:project(p)[2]})).sort((a,b)=>a.depth-b.depth).forEach(({p,i})=>{
  jointRing(p,f.axes[i],ringSize*(i===4?1.4:1),selected===i?'#ffcc8e':'#d9eeee');
  const axislen=ringSize*2.4;line(K.sub(p,K.scale(f.axes[i],axislen)),K.add(p,K.scale(f.axes[i],axislen)),i===0||i===4?'#75aaff':i===5?'#ff818b':'#7cd49c',1.5,[3,3]);
  if(i!==5||g.e56>1e-8)label(p,i===4&&g.e56<1e-8?'J5 · J6':g.h===0&&i===0?'J1 · J2':i===1&&g.h===0?'':`J${i+1}`,'#d5e8ed',i===3?-36:10,i===1?24:-13);
 });
 triad(f.tool.p,f.tool.R,unit*.4);label(f.tool.p,g.control==='tool'?'punta · activa':'punta','#f4e382',12,24);
 K.tr(f.camera.R).forEach((v,i)=>arrow(f.camera.p,v,['#ff777f','#69d591','#6baaff'][i],['x꜀','y꜀','z꜀'][i],unit*.25));label(f.camera.p,g.control==='camera'?'cámara · activa':'cámara','#ffffff',10,-27);
 ctx.fillStyle='#8a9bb6';ctx.font='12px ui-monospace,monospace';ctx.fillText(`Cuadrícula: ${fmt(step*100,0)} cm`,16,H-18);
 if(Math.min(...f.points.map(p=>p[2]))<-1e-6){ctx.fillStyle='#ffb36a';ctx.fillText('Parte del brazo está bajo z = 0',16,25);}
}
let drag=null;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';});
canvas.addEventListener('pointermove',e=>{if(!drag)return;camera.az-=(e.clientX-drag.x)*.009;camera.el=K.clamp(camera.el+(e.clientY-drag.y)*.008,-1.5,1.56);drag={x:e.clientX,y:e.clientY};draw();});
for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,()=>{drag=null;canvas.style.cursor='grab';});
canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=K.clamp(camera.zoom*Math.exp(-e.deltaY*.001),.4,3.5);draw();},{passive:false});
canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')camera.az-=.1;if(e.key==='ArrowRight')camera.az+=.1;if(e.key==='ArrowUp')camera.el=K.clamp(camera.el+.1,-1.5,1.56);if(e.key==='ArrowDown')camera.el=K.clamp(camera.el-.1,-1.5,1.56);if(e.key==='+')camera.zoom=K.clamp(camera.zoom*1.1,.4,3.5);if(e.key==='-')camera.zoom=K.clamp(camera.zoom/1.1,.4,3.5);draw();});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;camera={az:v==='front'?-Math.PI/2:-1,el:v==='front'?0:v==='top'?Math.PI/2:.48,zoom:1};document.querySelectorAll('[data-view]').forEach(btn=>btn.classList.toggle('active',btn===b));draw();});

// Transport only: poses, axes and origins have already been computed in Python.
window.setArmSnapshot=data=>{
 snapshot=data;g=data.geometry;target=data.preview;
 $('feedback').textContent=data.status;
 draw();
};
window.armPointer=event=>{
 canvas.dispatchEvent(new PointerEvent(event.type,{...event,pointerId:1,bubbles:true}));
};
// Synthetic pointer events used by Tk cannot acquire browser pointer capture.
canvas.setPointerCapture=()=>{};
window.armWheel=deltaY=>canvas.dispatchEvent(new WheelEvent('wheel',{deltaY,cancelable:true}));
window.armKey=key=>canvas.dispatchEvent(new KeyboardEvent('keydown',{key,cancelable:true}));
window.armView=view=>document.querySelector(`[data-view="${view}"]`).click();
new ResizeObserver(resize).observe(canvas);
