"""Extract the delivered Canvas verbatim, replacing only its FK data source.

Run from any directory. No IK, FK or trajectory solver is shipped to the
integrated renderer. The standalone demonstration remains byte-for-byte intact.
"""
from pathlib import Path

PACKAGE = Path(__file__).resolve().parents[1]


def generate():
    original = (PACKAGE / 'simulador_web_original/dist/app.js').read_text(encoding='utf-8')
    start = original.index("const canvas=$('scene')")
    renderer = original[start:original.index('capture();message(', start)]
    renderer = renderer.replace('if(!W||!H)return;', 'if(!W||!H||!snapshot)return;')
    renderer = renderer.replace('const f=K.fk(q,g),reach=', 'const f=snapshot.fk,reach=')
    # Only the vector helpers used for drawing, copied from the delivered web.
    helpers = (PACKAGE / 'simulador_web_original/dist/kinematics.js').read_text(encoding='utf-8')
    vectors = helpers[helpers.index('const add='):helpers.index('const rx=')]
    preamble = """// GENERATED by tools/extract_arm_canvas.py from the delivered renderer.
'use strict';
const $=id=>document.getElementById(id);
""" + vectors + """
const K={add,sub,scale,dot,norm,cross,tr,mv,clamp:(v,a,b)=>Math.min(b,Math.max(a,v))};
let snapshot=null,g={},target=null,selected=-1,mode='pose';
let camera={az:-1.1,el:.24,zoom:1};
const fmt=(v,n=2)=>{let x=Math.abs(v)<.5*10**(-n)?0:v;return x.toFixed(n);};
window.MotionUI={drawPath(){
 const points=snapshot.preview?.points;
 if(points)points.slice(1).forEach((p,i)=>line(points[i],p,'#ffb36a',3,[5,5]));
}};
"""
    bridge = """
// Transport only: poses, axes and origins have already been computed in Python.
window.setArmSnapshot=data=>{
 snapshot=data;g=data.geometry;target=data.preview;
 $('feedback').textContent=data.status;
 draw();
};
window.armPointer=event=>{
 canvas.dispatchEvent(new PointerEvent(event.type,{...event,pointerId:1,bubbles:true}));
};
// Synthetic pointer events used by Tk cannot acquire browser pointer capture.
canvas.setPointerCapture=()=>{};
window.armWheel=deltaY=>canvas.dispatchEvent(new WheelEvent('wheel',{deltaY,cancelable:true}));
window.armKey=key=>canvas.dispatchEvent(new KeyboardEvent('keydown',{key,cancelable:true}));
window.armView=view=>document.querySelector(`[data-view="${view}"]`).click();
new ResizeObserver(resize).observe(canvas);
"""
    destination = PACKAGE / 'rescue_command_station/arm/web_assets/canvas.js'
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(preamble + renderer + bridge, encoding='utf-8')


if __name__ == '__main__':
    generate()
